#!/usr/bin/php
<?php

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', true);

require_once 'ztest/ztest.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'environmentalist.php';

$reporter = new ztest\ConsoleReporter;
$reporter->enable_color();

$suite = new ztest\TestSuite('Environmentalist unit tests');
$suite->require_all(__DIR__.DIRECTORY_SEPARATOR.'unit');
$suite->auto_fill();
$suite->run($reporter);